# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icnsify < Formula
  desc ""
  homepage ""
  version "2.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JackMordaunt/icns/releases/download/v2.2.4/icns_2.2.4_darwin_arm64.tar.gz"
      sha256 "ea5d76e4fda61eb960aeaaf7bf973941630786403866ad314c968d66bcadb456"

      def install
        bin.install "icnsify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JackMordaunt/icns/releases/download/v2.2.4/icns_2.2.4_darwin_amd64.tar.gz"
      sha256 "96636f37b8b0aa7198077b5a495f8d2f154f607d9b107cd63a1a3af14294529d"

      def install
        bin.install "icnsify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JackMordaunt/icns/releases/download/v2.2.4/icns_2.2.4_linux_amd64.tar.gz"
      sha256 "7e075f41e4a7115af6fa3cc02e8b977c9d8ea26bc652531df48b44f373db488c"

      def install
        bin.install "icnsify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JackMordaunt/icns/releases/download/v2.2.4/icns_2.2.4_linux_arm64.tar.gz"
      sha256 "f60f35ba9c5a15f149d3b39ad004c2b7c80103ca8f06f740617aada163ddab70"

      def install
        bin.install "icnsify"
      end
    end
  end
end
